FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    git \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /py
RUN pip install --upgrade pip 
COPY requirements.txt .

RUN pip install -r requirements.txt
